In [ ]:
!pip install -q "zarr>=3.0.10" "tracksdata @ git+https://github.com/royerlab/tracksdata@main" scipy tqdm

In [2]:
import torch
import zarr
import scipy
import numpy as np
import tracksdata

print("PyTorch    :", torch.__version__)
print("Zarr       :", zarr.__version__)
print("SciPy      :", scipy.__version__)
print("NumPy      :", np.__version__)
print("tracksdata :", "OK")

PyTorch    : 2.10.0+cu128
Zarr       : 3.3.0
SciPy      : 1.16.3
NumPy      : 2.5.3
tracksdata : OK


In [7]:
from pathlib import Path

COMPETITION_DIR = Path(
    "/kaggle/input/competitions/biohub-cell-tracking-during-development"
)

TRAIN_DIR = COMPETITION_DIR / "train"
TEST_DIR = COMPETITION_DIR / "test"

print("Competition directory:", COMPETITION_DIR)
print("Train exists:", TRAIN_DIR.exists())
print("Test exists:", TEST_DIR.exists())

Competition directory: /kaggle/input/competitions/biohub-cell-tracking-during-development
Train exists: True
Test exists: True


In [8]:
from pathlib import Path

INPUT_DIR = Path("/kaggle/input")

for item in sorted(INPUT_DIR.iterdir()):
    print(item)

/kaggle/input/competitions
/kaggle/input/notebooks


In [9]:
from pathlib import Path

BASELINE = Path(
    "/kaggle/input/notebooks/thibautgoldsborough/"
    "unet-baseline-inference-submission"
)

print("Baseline:", BASELINE)
print("Weights:")
for p in (BASELINE / "repo/weights").rglob("*"):
    if p.is_file():
        print(" ", p)

Baseline: /kaggle/input/notebooks/thibautgoldsborough/unet-baseline-inference-submission
Weights:
  /kaggle/input/notebooks/thibautgoldsborough/unet-baseline-inference-submission/repo/weights/unet_transformer/split_0/config.json
  /kaggle/input/notebooks/thibautgoldsborough/unet-baseline-inference-submission/repo/weights/unet_transformer/split_0/edge_predictor_best.pth


In [10]:
import json
from pathlib import Path

config_path = Path(
    "/kaggle/input/notebooks/thibautgoldsborough/"
    "unet-baseline-inference-submission/"
    "repo/weights/unet_transformer/split_0/config.json"
)

with open(config_path) as f:
    config = json.load(f)

print(json.dumps(config, indent=2))

{
  "unet_out_channels": 32,
  "unet_layers": [
    32,
    64,
    128
  ],
  "downsample": [
    1,
    4,
    4
  ],
  "window_size": 2,
  "pool_kernel_um": 5.0
}


In [11]:
import torch

weights_path = Path(
    "/kaggle/input/notebooks/thibautgoldsborough/"
    "unet-baseline-inference-submission/"
    "repo/weights/unet_transformer/split_0/edge_predictor_best.pth"
)

checkpoint = torch.load(weights_path, map_location="cpu", weights_only=False)

print(type(checkpoint))

if isinstance(checkpoint, dict):
    print("\nCheckpoint keys:")
    for k in checkpoint.keys():
        print(" ", k)

<class 'dict'>

Checkpoint keys:
  unet.encoder_blocks.0.0.weight
  unet.encoder_blocks.0.1.weight
  unet.encoder_blocks.0.1.bias
  unet.encoder_blocks.0.1.running_mean
  unet.encoder_blocks.0.1.running_var
  unet.encoder_blocks.0.1.num_batches_tracked
  unet.encoder_blocks.0.3.weight
  unet.encoder_blocks.0.4.weight
  unet.encoder_blocks.0.4.bias
  unet.encoder_blocks.0.4.running_mean
  unet.encoder_blocks.0.4.running_var
  unet.encoder_blocks.0.4.num_batches_tracked
  unet.encoder_blocks.1.0.weight
  unet.encoder_blocks.1.1.weight
  unet.encoder_blocks.1.1.bias
  unet.encoder_blocks.1.1.running_mean
  unet.encoder_blocks.1.1.running_var
  unet.encoder_blocks.1.1.num_batches_tracked
  unet.encoder_blocks.1.3.weight
  unet.encoder_blocks.1.4.weight
  unet.encoder_blocks.1.4.bias
  unet.encoder_blocks.1.4.running_mean
  unet.encoder_blocks.1.4.running_var
  unet.encoder_blocks.1.4.num_batches_tracked
  unet.encoder_blocks.2.0.weight
  unet.encoder_blocks.2.1.weight
  unet.encoder_blocks

In [12]:
import torch
import zarr
import scipy
import numpy as np

print("PyTorch :", torch.__version__)
print("Zarr    :", zarr.__version__)
print("SciPy   :", scipy.__version__)
print("NumPy   :", np.__version__)

try:
    import tracksdata
    print("tracksdata: OK")
except Exception as e:
    print("tracksdata: ERROR")
    print(e)

PyTorch : 2.10.0+cu128
Zarr    : 3.3.0
SciPy   : 1.16.3
NumPy   : 2.5.3
tracksdata: OK


In [13]:
from pathlib import Path
import shutil
import sys

BASELINE_REPO = Path(
    "/kaggle/input/notebooks/thibautgoldsborough/"
    "unet-baseline-inference-submission/repo"
)

REPO_DIR = Path("/kaggle/working/repo")

shutil.copytree(BASELINE_REPO, REPO_DIR, dirs_exist_ok=True)

sys.path.insert(0, str(REPO_DIR / "src"))

print("Repo:", REPO_DIR)
print("Exists:", REPO_DIR.exists())
print("Source:", REPO_DIR / "src")

Repo: /kaggle/working/repo
Exists: True
Source: /kaggle/working/repo/src


In [14]:
from tracking_cellmot.models.temporal_unet import TemporalUNet3D
from tracking_cellmot.models.simple_node_transformer import SimpleNodeTransformer

print("TemporalUNet3D :", TemporalUNet3D)
print("SimpleNodeTransformer :", SimpleNodeTransformer)

TemporalUNet3D : <class 'tracking_cellmot.models.temporal_unet.TemporalUNet3D'>
SimpleNodeTransformer : <class 'tracking_cellmot.models.simple_node_transformer.SimpleNodeTransformer'>


In [15]:
import json
import torch
from pathlib import Path

config_path = Path(
    "/kaggle/input/notebooks/thibautgoldsborough/"
    "unet-baseline-inference-submission/"
    "repo/weights/unet_transformer/split_0/config.json"
)

weights_path = Path(
    "/kaggle/input/notebooks/thibautgoldsborough/"
    "unet-baseline-inference-submission/"
    "repo/weights/unet_transformer/split_0/edge_predictor_best.pth"
)

with open(config_path) as f:
    config = json.load(f)

checkpoint = torch.load(
    weights_path,
    map_location="cpu",
    weights_only=False
)

print("Config:")
for k, v in config.items():
    print(f"  {k}: {v}")

print("\nCheckpoint tensors:", len(checkpoint))
print("First 5:")
for k in list(checkpoint.keys())[:5]:
    print(f"  {k}: {tuple(checkpoint[k].shape)}")

Config:
  unet_out_channels: 32
  unet_layers: [32, 64, 128]
  downsample: [1, 4, 4]
  window_size: 2
  pool_kernel_um: 5.0

Checkpoint tensors: 136
First 5:
  unet.encoder_blocks.0.0.weight: (32, 1, 3, 3, 3)
  unet.encoder_blocks.0.1.weight: (32,)
  unet.encoder_blocks.0.1.bias: (32,)
  unet.encoder_blocks.0.1.running_mean: (32,)
  unet.encoder_blocks.0.1.running_var: (32,)


In [16]:
import torch
from tracking_cellmot.models.temporal_unet import TemporalUNet3D
from tracking_cellmot.models.simple_node_transformer import SimpleNodeTransformer

# Build the exact architecture from the released config
unet = TemporalUNet3D(
    in_channels=1,
    out_channels=config["unet_out_channels"],
    layers=tuple(config["unet_layers"]),
)

transformer = SimpleNodeTransformer(
    feat_dim=config["unet_out_channels"] + 32,
)

print("UNet created:")
print(unet)

print("\nTransformer created:")
print(transformer)

print("\nModel components created successfully.")

UNet created:
TemporalUNet3D(
  (encoder_blocks): ModuleList(
    (0): Sequential(
      (0): Conv3d(1, 32, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), bias=False)
      (1): BatchNorm3d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
      (3): Conv3d(32, 32, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), bias=False)
      (4): BatchNorm3d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): ReLU(inplace=True)
    )
    (1): Sequential(
      (0): Conv3d(32, 64, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), bias=False)
      (1): BatchNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
      (3): Conv3d(64, 64, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), bias=False)
      (4): BatchNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): ReLU(inplace=True)
    )
    (2): 

## Load the Released Baseline Model

The released checkpoint contains the weights for the complete tracking model:

1. Temporal U-Net — extracts spatiotemporal features.
2. Detection head — predicts cell centers.
3. Node transformer — compares detected cells between consecutive frames.
4. Pairwise MLP — predicts whether two cells should be connected.

We reconstruct the same architecture and load the released weights with strict key matching.

In [17]:
from tracking_cellmot.models.temporal_unet import TemporalUNet3D
from tracking_cellmot.models.simple_node_transformer import SimpleNodeTransformer
from tracking_cellmot.models.temporal_unet import TemporalUNet3D
from tracking_cellmot.models.simple_node_transformer import SimpleNodeTransformer
import torch.nn as nn


class UNetNodeTransformer(nn.Module):
    def __init__(
        self,
        unet_out_channels=32,
        unet_layers=(32, 64, 128),
    ):
        super().__init__()

        self.unet = TemporalUNet3D(
            in_channels=1,
            out_channels=unet_out_channels,
            layers=unet_layers,
        )

        self.detect_head = nn.Conv3d(
            unet_out_channels,
            1,
            kernel_size=1,
        )

        self.transformer = SimpleNodeTransformer(
            feat_dim=unet_out_channels + 32,
        )


model = UNetNodeTransformer(
    unet_out_channels=config["unet_out_channels"],
    unet_layers=tuple(config["unet_layers"]),
)

print("Complete model created.")
print("Parameters:", sum(p.numel() for p in model.parameters()))

Complete model created.
Parameters: 2076706


In [18]:
load_result = model.load_state_dict(
    checkpoint,
    strict=True,
)

print(load_result)
print("\nAll checkpoint weights loaded successfully.")

<All keys matched successfully>

All checkpoint weights loaded successfully.


## Inspect a Test Dataset

The competition test data is stored as OME-Zarr arrays with dimensions:

`(T, Z, Y, X)`

Before running inference, we inspect one dataset to understand:

- number of frames (`T`)
- depth (`Z`)
- height (`Y`)
- width (`X`)
- available metadata
- voxel scale, if provided

In [19]:
from pathlib import Path
import zarr

DATA_DIR = Path(
    "/kaggle/input/competitions/"
    "biohub-cell-tracking-during-development"
)

TEST_DIR = DATA_DIR / "test"

test_datasets = sorted(TEST_DIR.glob("*.zarr"))

print("Number of test datasets:", len(test_datasets))
print("\nFirst 10 datasets:")

for path in test_datasets[:10]:
    print(" ", path.name)

Number of test datasets: 4

First 10 datasets:
  44b6_0113de3b.zarr
  44b6_0b24845f.zarr
  6bba_05b6850b.zarr
  6bba_05db0fb1.zarr


In [20]:
test_path = test_datasets[0]

print("Inspecting:")
print(test_path)

root = zarr.open(test_path, mode="r")

print("\nZarr object:")
print(root)

print("\nArray shape:", root.shape)
print("Array dtype:", root.dtype)

Inspecting:
/kaggle/input/competitions/biohub-cell-tracking-during-development/test/44b6_0113de3b.zarr

Zarr object:
<Group file:///kaggle/input/competitions/biohub-cell-tracking-during-development/test/44b6_0113de3b.zarr>


AttributeError: 'Group' object has no attribute 'shape'

In [21]:
print("Zarr group contents:\n")

def show_zarr_group(group, prefix=""):
    for name, item in group.items():
        path = f"{prefix}/{name}" if prefix else name

        if isinstance(item, zarr.Group):
            print(f"[GROUP] {path}")
            show_zarr_group(item, path)
        else:
            print(
                f"[ARRAY] {path} | "
                f"shape={item.shape} | "
                f"dtype={item.dtype}"
            )

show_zarr_group(root)

Zarr group contents:



AttributeError: 'Group' object has no attribute 'items'

In [23]:
print("Zarr group contents:\n")

print("Root keys:")
print(list(root.keys()))

print("\nRoot attributes:")
print(dict(root.attrs))

print("\nMembers:")
for key in root.keys():
    item = root[key]
    print(f"{key}: {type(item)}")

Zarr group contents:

Root keys:
['0']

Root attributes:
{'multiscales': [{'version': '0.5', 'axes': [{'name': 'T', 'type': 'time', 'unit': 'second'}, {'name': 'Z', 'type': 'space', 'unit': 'micrometer'}, {'name': 'Y', 'type': 'space', 'unit': 'micrometer'}, {'name': 'X', 'type': 'space', 'unit': 'micrometer'}], 'datasets': [{'path': '0', 'coordinateTransformations': [{'type': 'scale', 'scale': [1.0, 1.625, 0.40625, 0.40625]}]}], 'name': '0'}], 'image_statistics': {'quantiles': {'0.0': 15.0, '0.001': 26.222222222222225, '0.01': 38.0, '0.1': 75.0, '0.9': 497.0, '0.99': 1478.0, '0.999': 2145.000000039654, '1.0': 4319.0}}}

Members:
0: <class 'zarr.core.array.Array'>


In [24]:
image = root["0"]

print("Image array:")
print("  Shape :", image.shape)
print("  Dtype :", image.dtype)
print("  Chunks:", image.chunks)

print("\nDimensions:")
print(f"  T = {image.shape[0]}")
print(f"  Z = {image.shape[1]}")
print(f"  Y = {image.shape[2]}")
print(f"  X = {image.shape[3]}")

print("\nVoxel scale (µm):")
print("  T:", 1.0)
print("  Z:", 1.625)
print("  Y:", 0.40625)
print("  X:", 0.40625)

quantiles = root.attrs["image_statistics"]["quantiles"]

print("\nNormalization quantiles:")
print("  q0.001:", quantiles["0.001"])
print("  q0.999:", quantiles["0.999"])

Image array:
  Shape : (100, 64, 256, 256)
  Dtype : uint16
  Chunks: (1, 64, 256, 256)

Dimensions:
  T = 100
  Z = 64
  Y = 256
  X = 256

Voxel scale (µm):
  T: 1.0
  Z: 1.625
  Y: 0.40625
  X: 0.40625

Normalization quantiles:
  q0.001: 26.222222222222225
  q0.999: 2145.000000039654


## Inspect One Microscopy Frame

The test sample contains 100 frames of 3D microscopy data.

We load only frame 0 to inspect its intensity distribution and confirm the data before preprocessing.

In [25]:
import numpy as np

# Load only the first time frame
frame0 = image[0]

print("Frame 0")
print("  Shape :", frame0.shape)
print("  Dtype :", frame0.dtype)
print("  Min   :", frame0.min())
print("  Max   :", frame0.max())
print("  Mean  :", frame0.mean())
print("  Std   :", frame0.std())

print("\nPercentiles:")
for p in [0, 1, 50, 90, 99, 99.9, 100]:
    print(f"  {p:5.1f}% :", np.percentile(frame0, p))

Frame 0
  Shape : (64, 256, 256)
  Dtype : uint16
  Min   : 12
  Max   : 2950
  Mean  : 219.03385424613953
  Std   : 224.90790816432502

Percentiles:
    0.0% : 12.0
    1.0% : 37.0
   50.0% : 155.0
   90.0% : 389.0
   99.0% : 1283.0
   99.9% : 1912.6970000006258
  100.0% : 2950.0


## Baseline Intensity Normalization

The baseline uses the dataset-level 0.1% and 99.9% intensity quantiles.

For an image value `x`:

`normalized = (x - q_low) / (q_high - q_low)`

The result is then clamped to `[0, 1]`.

This reduces the effect of extreme bright or dark intensity values while keeping the normalization consistent across all frames.

In [26]:
q_low = float(quantiles["0.001"])
q_high = float(quantiles["0.999"])

frame0_float = frame0.astype(np.float32)

frame0_norm = (frame0_float - q_low) / (q_high - q_low + 1e-6)
frame0_norm = np.clip(frame0_norm, 0.0, 1.0)

print("Normalized frame 0")
print("  Shape :", frame0_norm.shape)
print("  Dtype :", frame0_norm.dtype)
print("  Min   :", frame0_norm.min())
print("  Max   :", frame0_norm.max())
print("  Mean  :", frame0_norm.mean())
print("  Std   :", frame0_norm.std())

print("\nNormalized percentiles:")
for p in [0, 1, 50, 90, 99, 99.9, 100]:
    print(f"  {p:5.1f}% :", np.percentile(frame0_norm, p))

Normalized frame 0
  Shape : (64, 256, 256)
  Dtype : float32
  Min   : 0.0
  Max   : 1.0
  Mean  : 0.090982646
  Std   : 0.10597214

Normalized percentiles:
    0.0% : 0.0
    1.0% : 0.0050867903
   50.0% : 0.06077927
   90.0% : 0.1712203
   99.0% : 0.5931617
   99.9% : 0.89035994
  100.0% : 1.0


## Spatial Downsampling

The baseline uses a downsampling factor of:

`[1, 4, 4]`

for `(T, Z, Y, X)`.

Therefore:

- T stays unchanged
- Z stays unchanged
- Y is reduced 4×
- X is reduced 4×

For one frame:

`(64, 256, 256) → (64, 64, 64)`

This also converts the original anisotropic spatial resolution into approximately isotropic voxels of `1.625 µm`.

In [28]:
import torch
import torch.nn.functional as F

# Convert the normalized frame to a PyTorch tensor
frame_tensor = torch.from_numpy(frame0_norm).unsqueeze(0).unsqueeze(0)

print("Before downsampling:")
print("  Shape:", tuple(frame_tensor.shape))

# [B, C, Z, Y, X]
# Downsample only Y and X by 4
frame_down = F.interpolate(
    frame_tensor,
    size=(
        frame_tensor.shape[2],
        frame_tensor.shape[3] // 4,
        frame_tensor.shape[4] // 4,
    ),
    mode="trilinear",
    align_corners=False,
)

print("\nAfter downsampling:")
print("  Shape:", tuple(frame_down.shape))
print("  Dtype:", frame_down.dtype)

print("\nSpatial dimensions:")
print("  Z:", frame_down.shape[2])
print("  Y:", frame_down.shape[3])
print("  X:", frame_down.shape[4])

Before downsampling:
  Shape: (1, 1, 64, 256, 256)

After downsampling:
  Shape: (1, 1, 64, 64, 64)
  Dtype: torch.float32

Spatial dimensions:
  Z: 64
  Y: 64
  X: 64


In [29]:
# Load two consecutive frames
frames = image[0:2].astype(np.float32)

# Normalize using the same dataset-level quantiles
frames = (frames - q_low) / (q_high - q_low + 1e-6)
frames = np.clip(frames, 0.0, 1.0)

# Convert to PyTorch
frames_tensor = torch.from_numpy(frames)

# Spatial downsampling
frames_tensor = F.interpolate(
    frames_tensor.unsqueeze(1),  # (T, C, Z, Y, X)
    size=(64, 64, 64),
    mode="trilinear",
    align_corners=False,
)

# Add batch dimension
frames_tensor = frames_tensor.unsqueeze(0)

print("Input tensor:")
print("  Shape:", tuple(frames_tensor.shape))
print("  Dtype:", frames_tensor.dtype)
print("  Min:", frames_tensor.min().item())
print("  Max:", frames_tensor.max().item())

Input tensor:
  Shape: (1, 2, 1, 64, 64, 64)
  Dtype: torch.float32
  Min: 0.0008652789983898401
  Max: 1.0


In [30]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = model.to(device)
model.eval()

frames_tensor = frames_tensor.to(device)

with torch.inference_mode():
    unet_features = model.unet(frames_tensor)

print("U-Net output:")
print("  Shape:", tuple(unet_features.shape))
print("  Dtype:", unet_features.dtype)

U-Net output:
  Shape: (1, 2, 32, 64, 64, 64)
  Dtype: torch.float32


## Cell Detection Head

The Temporal U-Net produces 32 learned features per voxel.

The detection head reduces these 32 features to one scalar:

`32 features → 1 detection logit`

Applying a sigmoid converts the logit into a value between 0 and 1, representing the model's confidence that a cell center is present at that voxel.

In [33]:
import torch

B, T, C, Z, Y, X = unet_features.shape

# Merge batch and time so Conv3D can process each frame
features_5d = unet_features.reshape(B * T, C, Z, Y, X)

with torch.inference_mode():
    detection_logits = model.detect_head(features_5d)
    detection_prob = torch.sigmoid(detection_logits)

# Restore [B, T, 1, Z, Y, X]
detection_logits = detection_logits.reshape(B, T, 1, Z, Y, X)
detection_prob = detection_prob.reshape(B, T, 1, Z, Y, X)

print("Detection logits:")
print("  Shape:", tuple(detection_logits.shape))
print("  Min:", detection_logits.min().item())
print("  Max:", detection_logits.max().item())

print("\nDetection probabilities:")
print("  Shape:", tuple(detection_prob.shape))
print("  Min:", detection_prob.min().item())
print("  Max:", detection_prob.max().item())
print("  Mean:", detection_prob.mean().item())

Detection logits:
  Shape: (1, 2, 1, 64, 64, 64)
  Min: -5.460357666015625
  Max: 17.01726531982422

Detection probabilities:
  Shape: (1, 2, 1, 64, 64, 64)
  Min: 0.004234031308442354
  Max: 1.0
  Mean: 0.15266656875610352


In [36]:
import torch.nn.functional as F

# Use frame 0 for inspection
prob = detection_prob[0, 0, 0]  # [Z, Y, X]

# Baseline inference threshold
threshold = 0.99

# Voxels above the threshold
above_threshold = prob >= threshold

print("Frame 0 detection map:")
print("  Shape:", tuple(prob.shape))
print("  Threshold:", threshold)
print("  Voxels >= threshold:", above_threshold.sum().item())
print("  Total voxels:", prob.numel())
print("  Percentage:", 
      100 * above_threshold.sum().item() / prob.numel())

# Show the strongest voxel
max_value, max_idx = prob.reshape(-1).max(0)

z, y, x = np.unravel_index(
    max_idx.item(),
    prob.shape
)

print("\nStrongest detection:")
print("  Probability:", max_value.item())
print("  Location (z, y, x):", (z, y, x))

Frame 0 detection map:
  Shape: (64, 64, 64)
  Threshold: 0.99
  Voxels >= threshold: 4794
  Total voxels: 262144
  Percentage: 1.828765869140625

Strongest detection:
  Probability: 1.0
  Location (z, y, x): (np.int64(20), np.int64(44), np.int64(20))


In [37]:
# Detection probability for frame 0
prob = detection_prob[0, 0, 0]

# Physical pooling size used by the baseline
pool_kernel_um = 5.0

# Effective voxel size after [1, 4, 4] downsampling
voxel_size_um = 1.625

# Convert physical size to an odd voxel kernel
kernel_size = int(round(pool_kernel_um / voxel_size_um))

if kernel_size % 2 == 0:
    kernel_size += 1

kernel_size = max(kernel_size, 3)

print("Physical pooling size:", pool_kernel_um, "µm")
print("Effective voxel size:", voxel_size_um, "µm")
print("Pooling kernel:", kernel_size, "x", kernel_size, "x", kernel_size)

# Max pooling finds the largest value in each local neighborhood
pooled = F.max_pool3d(
    prob[None, None],
    kernel_size=kernel_size,
    stride=1,
    padding=kernel_size // 2,
)

# A voxel is a local maximum if it equals the local maximum
local_max = prob[None, None] == pooled

# Keep only strong local maxima
threshold = 0.99
detections = local_max & (prob[None, None] >= threshold)

# Extract coordinates
coords = torch.nonzero(detections[0, 0], as_tuple=False)

# Extract probabilities at those coordinates
scores = prob[
    coords[:, 0],
    coords[:, 1],
    coords[:, 2]
]

print("\nLocal-max detections:")
print("  Number of detected cells:", len(coords))

if len(coords) > 0:
    print("  Score min:", scores.min().item())
    print("  Score max:", scores.max().item())
    print("  Score mean:", scores.mean().item())

    print("\nFirst 10 detections:")
    for coord, score in zip(coords[:10], scores[:10]):
        print(
            " ",
            tuple(coord.cpu().numpy()),
            "score=",
            round(score.item(), 4)
        )

Physical pooling size: 5.0 µm
Effective voxel size: 1.625 µm
Pooling kernel: 3 x 3 x 3

Local-max detections:
  Number of detected cells: 229
  Score min: 0.9910848736763
  Score max: 1.0
  Score mean: 0.99969881772995

First 10 detections:
  (np.int64(1), np.int64(1), np.int64(13)) score= 0.9996
  (np.int64(1), np.int64(1), np.int64(17)) score= 0.9995
  (np.int64(1), np.int64(6), np.int64(16)) score= 0.9981
  (np.int64(1), np.int64(15), np.int64(14)) score= 1.0
  (np.int64(1), np.int64(24), np.int64(8)) score= 1.0
  (np.int64(1), np.int64(26), np.int64(18)) score= 0.9911
  (np.int64(1), np.int64(31), np.int64(17)) score= 1.0
  (np.int64(1), np.int64(40), np.int64(6)) score= 0.9998
  (np.int64(1), np.int64(44), np.int64(15)) score= 0.9998
  (np.int64(1), np.int64(46), np.int64(9)) score= 1.0


In [38]:

print("Detection count across the first 2 frames:")

for t in range(T):
    prob_t = detection_prob[0, t, 0]

    pooled_t = F.max_pool3d(
        prob_t[None, None],
        kernel_size=kernel_size,
        stride=1,
        padding=kernel_size // 2,
    )

    local_max_t = prob_t[None, None] == pooled_t
    detections_t = local_max_t & (prob_t[None, None] >= threshold)

    coords_t = torch.nonzero(
        detections_t[0, 0],
        as_tuple=False
    )

    print(f"  Frame {t}: {len(coords_t)} detections")

Detection count across the first 2 frames:
  Frame 0: 229 detections
  Frame 1: 228 detections


In [43]:
import sys
from pathlib import Path
import importlib.util
import inspect

repo_dir = Path("/kaggle/working/repo")
predict_script = repo_dir / "scripts" / "predict_unet_transformer.py"

print("Prediction script:", predict_script)
print("Exists:", predict_script.exists())

# Load the script directly
spec = importlib.util.spec_from_file_location(
    "predict_unet_transformer",
    predict_script
)

predict_module = importlib.util.module_from_spec(spec)
sys.modules["predict_unet_transformer"] = predict_module
spec.loader.exec_module(predict_module)

print("\n_detect_cells_pooled signature:")
print(inspect.signature(predict_module._detect_cells_pooled))

Prediction script: /kaggle/working/repo/scripts/predict_unet_transformer.py
Exists: True

_detect_cells_pooled signature:
(det_logits: torch.Tensor, t: int, det_threshold: float = 0.5, pool_kernel: tuple[int, ...] = (3, 3, 3)) -> numpy.ndarray


In [39]:
from scipy.spatial.distance import pdist

coords_np = coords.cpu().numpy()

if len(coords_np) >= 2:
    # Coordinates are currently in downsampled voxel space.
    # Convert Z/Y/X to micrometers.
    coords_um = coords_np.astype(np.float32) * np.array(
        [1.625, 1.625, 1.625],
        dtype=np.float32
    )

    pairwise_distances = pdist(coords_um)

    print("Detection spacing:")
    print("  Number of detections:", len(coords_um))
    print("  Minimum pairwise distance:",
          pairwise_distances.min(), "µm")
    print("  Median pairwise distance:",
          np.median(pairwise_distances), "µm")
    print("  25th percentile:",
          np.percentile(pairwise_distances, 25), "µm")
    print("  75th percentile:",
          np.percentile(pairwise_distances, 75), "µm")

Detection spacing:
  Number of detections: 229
  Minimum pairwise distance: 1.625 µm
  Median pairwise distance: 62.80998129278499 µm
  25th percentile: 41.269881572400955 µm
  75th percentile: 85.36278174968696 µm


In [46]:
detect_cells_pooled = predict_module._detect_cells_pooled

# Remove the single-channel dimension:
# [B, T, 1, Z, Y, X] → [B, T, Z, Y, X]
det_logits = detection_logits.squeeze(2)

pool_kernel = (3, 3, 3)
det_threshold = 0.99

baseline_detections = {}

# We only have batch item 0 in this experiment
batch_idx = 0

for t in range(T):
    coords_t = detect_cells_pooled(
        det_logits[batch_idx],
        t=t,
        det_threshold=det_threshold,
        pool_kernel=pool_kernel,
    )

    baseline_detections[t] = coords_t

    print(f"Frame {t}:")
    print("  Shape:", coords_t.shape)
    print("  Number of detections:", len(coords_t))

    if len(coords_t) > 0:
        print("  First 10 coordinates:")
        print(coords_t[:10])

Frame 0:
  Shape: (228, 4)
  Number of detections: 228
  First 10 coordinates:
[[ 0  1  1 13]
 [ 0  1  1 17]
 [ 0  1  6 16]
 [ 0  1 15 14]
 [ 0  1 24  8]
 [ 0  1 26 18]
 [ 0  1 31 17]
 [ 0  1 40  6]
 [ 0  1 44 15]
 [ 0  1 46  9]]
Frame 1:
  Shape: (228, 4)
  Number of detections: 228
  First 10 coordinates:
[[ 1  1  1 13]
 [ 1  1  1 17]
 [ 1  1  6 16]
 [ 1  1 15 14]
 [ 1  1 24  8]
 [ 1  1 26 18]
 [ 1  1 31 17]
 [ 1  1 40  6]
 [ 1  1 44 15]
 [ 1  1 46  9]]


In [49]:
# Extract the detected coordinates for both frames
coords_0 = baseline_detections[0]
coords_1 = baseline_detections[1]

print("Frame 0 detections:", coords_0.shape)
print("Frame 1 detections:", coords_1.shape)

# Remove the time column because we already selected the frame
xyz_0 = torch.from_numpy(coords_0[:, 1:]).long().to(device)
xyz_1 = torch.from_numpy(coords_1[:, 1:]).long().to(device)

# U-Net features:
# [B, T, C, Z, Y, X]
features_0 = unet_features[0, 0]
features_1 = unet_features[0, 1]

# Index the feature map at every detected cell center
node_features_0 = features_0[
    :,
    xyz_0[:, 0],
    xyz_0[:, 1],
    xyz_0[:, 2],
].T

node_features_1 = features_1[
    :,
    xyz_1[:, 0],
    xyz_1[:, 1],
    xyz_1[:, 2],
].T

print("\nNode features:")
print("  Frame 0:", tuple(node_features_0.shape))
print("  Frame 1:", tuple(node_features_1.shape))

print("\nFeature dimension:", node_features_0.shape[1])
print("Expected:", config["unet_out_channels"])

Frame 0 detections: (228, 4)
Frame 1 detections: (228, 4)

Node features:
  Frame 0: (228, 32)
  Frame 1: (228, 32)

Feature dimension: 32
Expected: 32


In [ ]:
## Step 7 — Add positional features

The U-Net gives each detected cell 32 learned visual features.

The baseline also represents the cell's position using sinusoidal positional
features over:

- time `t`
- depth `z`
- height `y`
- width `x`

There are 8 features for each coordinate, giving 32 positional features.

These are concatenated with the 32 U-Net features:

$$
32\text{ visual} + 32\text{ positional} = 64\text{ Transformer features}
$$

In [52]:
extract_pos_features = predict_module.extract_pos_features

# Keep coordinates as NumPy arrays
pos_0 = coords_0.astype(np.float32)
pos_1 = coords_1.astype(np.float32)

# Downsampled spatial shape used by the U-Net
image_shape = (64, 64, 64)

pos_features_0 = extract_pos_features(pos_0, image_shape)
pos_features_1 = extract_pos_features(pos_1, image_shape)

print("Positional features:")
print("  Frame 0:", pos_features_0.shape)
print("  Frame 1:", pos_features_1.shape)

print("\nPositional feature dimension:", pos_features_0.shape[1])
print("dtype:", pos_features_0.dtype)

Positional features:
  Frame 0: (228, 24)
  Frame 1: (228, 24)

Positional feature dimension: 24
dtype: float32


In [53]:
pos_features_0 = torch.from_numpy(pos_features_0).to(device)
pos_features_1 = torch.from_numpy(pos_features_1).to(device)

node_input_0 = torch.cat([node_features_0, pos_features_0], dim=1)
node_input_1 = torch.cat([node_features_1, pos_features_1], dim=1)

print("Transformer input:")
print("  Frame 0:", node_input_0.shape)
print("  Frame 1:", node_input_1.shape)

Transformer input:
  Frame 0: torch.Size([228, 56])
  Frame 1: torch.Size([228, 56])


In [54]:
import inspect

print(inspect.signature(extract_pos_features))
print(inspect.getsource(extract_pos_features))

(coords: numpy.ndarray, image_shape: tuple[int, ...], pos_embed_dim: int = 8) -> numpy.ndarray
def extract_pos_features(
    coords: np.ndarray,
    image_shape: tuple[int, ...],
    pos_embed_dim: int = _POS_EMBED_DIM,
) -> np.ndarray:
    """Sinusoidal positional embeddings for node coordinates (no intensity term).

    Parameters
    ----------
    coords : np.ndarray
        (N, 4) with columns [t, z, y, x].
    image_shape : tuple
        Full image shape (T, Z, Y, X) used for normalisation.
    pos_embed_dim : int
        Half-dimension per axis (sin half + cos half).

    Returns
    -------
    np.ndarray
        Shape (N, 4 * pos_embed_dim), float32.
    """
    t, z, y, x = coords[:, 0], coords[:, 1], coords[:, 2], coords[:, 3]
    norms = [c / max(s, 1) for c, s in zip([t, z, y, x], image_shape)]

    def _embed(vals: np.ndarray) -> np.ndarray:
        freqs = 2 ** np.arange(pos_embed_dim // 2)
        angles = vals[:, None] * freqs * np.pi
        return np.concatenate([np.

In [55]:
print("_POS_EMBED_DIM:", predict_module._POS_EMBED_DIM)
print("Expected positional dimension:", 4 * predict_module._POS_EMBED_DIM)

_POS_EMBED_DIM: 8
Expected positional dimension: 32


In [59]:
print("Function module:")
print(extract_pos_features.__module__)

print("\nFunction source:")
import inspect
print(inspect.getsource(extract_pos_features))

print("Prediction module _POS_EMBED_DIM:")
print(getattr(predict_module, "_POS_EMBED_DIM", "NOT DEFINED"))

print("\nTraining module _POS_EMBED_DIM:")
print(getattr(train_module, "_POS_EMBED_DIM", "NOT DEFINED"))

import importlib.util

spec = importlib.util.spec_from_file_location(
    "train_module",
    "/kaggle/working/repo/scripts/train_unet_transformer.py"
)
train_module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(train_module)

print(train_module._POS_EMBED_DIM)

Function module:
train_unet_transformer

Function source:
def extract_pos_features(
    coords: np.ndarray,
    image_shape: tuple[int, ...],
    pos_embed_dim: int = _POS_EMBED_DIM,
) -> np.ndarray:
    """Sinusoidal positional embeddings for node coordinates (no intensity term).

    Parameters
    ----------
    coords : np.ndarray
        (N, 4) with columns [t, z, y, x].
    image_shape : tuple
        Full image shape (T, Z, Y, X) used for normalisation.
    pos_embed_dim : int
        Half-dimension per axis (sin half + cos half).

    Returns
    -------
    np.ndarray
        Shape (N, 4 * pos_embed_dim), float32.
    """
    t, z, y, x = coords[:, 0], coords[:, 1], coords[:, 2], coords[:, 3]
    norms = [c / max(s, 1) for c, s in zip([t, z, y, x], image_shape)]

    def _embed(vals: np.ndarray) -> np.ndarray:
        freqs = 2 ** np.arange(pos_embed_dim // 2)
        angles = vals[:, None] * freqs * np.pi
        return np.concatenate([np.sin(angles), np.cos(angles)], axis=1)

NameError: name 'train_module' is not defined

In [60]:
# Full image shape: (T, Z, Y, X)
image_shape = tuple(image.shape)

print("Full image shape:", image_shape)

pos_features_0 = extract_pos_features(coords_0.astype(np.float32), image_shape)
pos_features_1 = extract_pos_features(coords_1.astype(np.float32), image_shape)

print("\nPositional features:")
print("  Frame 0:", pos_features_0.shape)
print("  Frame 1:", pos_features_1.shape)

print("\nPositional feature dimension:", pos_features_0.shape[1])

Full image shape: (100, 64, 256, 256)

Positional features:
  Frame 0: (228, 32)
  Frame 1: (228, 32)

Positional feature dimension: 32


In [61]:
pos_features_0 = torch.from_numpy(pos_features_0).to(device)
pos_features_1 = torch.from_numpy(pos_features_1).to(device)

node_input_0 = torch.cat(
    [node_features_0, pos_features_0],
    dim=1
)

node_input_1 = torch.cat(
    [node_features_1, pos_features_1],
    dim=1
)

print("Transformer input:")
print("  Frame 0:", node_input_0.shape)
print("  Frame 1:", node_input_1.shape)

Transformer input:
  Frame 0: torch.Size([228, 64])
  Frame 1: torch.Size([228, 64])


In [62]:
with torch.inference_mode():
    edge_logits = model.transformer(
        node_input_0,
        node_input_1,
        xyz_0.float(),
        xyz_1.float(),
    )

print("Edge logits shape:", edge_logits.shape)
print("Min:", edge_logits.min().item())
print("Max:", edge_logits.max().item())

Edge logits shape: torch.Size([228, 228])
Min: -15.193598747253418
Max: 1.9708455801010132


In [64]:
edge_probs = torch.softmax(edge_logits, dim=1)

print("Edge probabilities shape:", edge_probs.shape)
print("Min:", edge_probs.min().item())
print("Max:", edge_probs.max().item())

row_sums = edge_probs.sum(dim=1)

print("Row sum min:", row_sums.min().item())
print("Row sum max:", row_sums.max().item())

Edge probabilities shape: torch.Size([228, 228])
Min: 2.456572190112638e-08
Max: 0.562430202960968
Row sum min: 0.9999998807907104
Row sum max: 1.0000001192092896


In [65]:
best_targets = torch.argmax(edge_probs, dim=1)
best_probs = edge_probs[
    torch.arange(edge_probs.shape[0], device=edge_probs.device),
    best_targets
]

print("First 20 predicted edges:\n")

for i in range(20):
    src = coords_0[i]
    tgt = coords_1[best_targets[i].item()]
    prob = best_probs[i].item()

    print(
        f"{i:3d}: "
        f"t={src[0]}, "
        f"({src[1]:2d},{src[2]:2d},{src[3]:2d}) "
        f"-> "
        f"({tgt[1]:2d},{tgt[2]:2d},{tgt[3]:2d}) "
        f"prob={prob:.4f}"
    )

First 20 predicted edges:

  0: t=0, ( 1, 1,13) -> ( 1, 1,13) prob=0.4402
  1: t=0, ( 1, 1,17) -> ( 1, 1,13) prob=0.4611
  2: t=0, ( 1, 6,16) -> ( 1, 1,13) prob=0.5624
  3: t=0, ( 1,15,14) -> ( 1,24, 8) prob=0.2537
  4: t=0, ( 1,24, 8) -> ( 2,21,22) prob=0.1653
  5: t=0, ( 1,26,18) -> ( 1,26,18) prob=0.4694
  6: t=0, ( 1,31,17) -> ( 2,21,22) prob=0.1580
  7: t=0, ( 1,40, 6) -> ( 1,40, 6) prob=0.2916
  8: t=0, ( 1,44,15) -> ( 1,40, 6) prob=0.1909
  9: t=0, ( 1,46, 9) -> ( 1,40, 6) prob=0.2093
 10: t=0, ( 1,52,15) -> ( 1,44,15) prob=0.1798
 11: t=0, ( 1,53, 7) -> ( 1,53, 7) prob=0.1779
 12: t=0, ( 1,58, 8) -> ( 1,52,15) prob=0.1881
 13: t=0, ( 1,61,16) -> ( 1,61,16) prob=0.3304
 14: t=0, ( 2, 8,17) -> ( 1, 6,16) prob=0.2761
 15: t=0, ( 2,21,22) -> ( 2,21,22) prob=0.1971
 16: t=0, ( 2,23,14) -> ( 1,24, 8) prob=0.1834
 17: t=0, ( 2,36,19) -> ( 1,40, 6) prob=0.1606
 18: t=0, ( 2,36,26) -> ( 1,46, 9) prob=0.0602
 19: t=0, ( 3,36,11) -> ( 6,30,13) prob=0.1285


In [66]:
print("\nBest-edge probability statistics:")
print("Mean  :", best_probs.mean().item())
print("Median:", best_probs.median().item())
print("Max   :", best_probs.max().item())
print("Min   :", best_probs.min().item())

for threshold in [0.1, 0.2, 0.3, 0.4, 0.5]:
    count = (best_probs >= threshold).sum().item()
    print(f">= {threshold:.1f}: {count}/{len(best_probs)}")


Best-edge probability statistics:
Mean  : 0.19789351522922516
Median: 0.18182483315467834
Max   : 0.562430202960968
Min   : 0.06016438826918602
>= 0.1: 214/228
>= 0.2: 94/228
>= 0.3: 19/228
>= 0.4: 9/228
>= 0.5: 2/228


In [67]:
import inspect

print(inspect.getsource(predict_module.predict_video))

@torch.no_grad()
def predict_video(
    model: UNetNodeTransformer,
    ds_path: Path,
    device: torch.device,
    cfg: PredictConfig,
    window_size: int = 2,
    max_frames: int | None = None,
    unet_batch_size: int = 4,
    downsample: tuple[int, ...] = (1, 4, 4),
) -> tuple[np.ndarray, list[tuple[int, int, float, float]]]:
    """Run inference on a single video using sliding windows of W frames.

    Windows slide with stride ``W - 1`` so every consecutive pair is covered
    exactly once.  UNet features from each window are reused for edge
    prediction on all ``W - 1`` consecutive pairs within the window.

    Returns
    -------
    coords : np.ndarray
        Shape (N, 4) — columns [t, z, y, x] in original resolution.
    edges : list of (src_idx, tgt_idx, prob, distance) tuples
    """
    ds = open_dataset(ds_path, normalize=False, load_image=False, downsample=downsample)
    if "0.001" not in ds.quantiles or "0.999" not in ds.quantiles:
        raise ValueError(f"Zarr 

In [68]:
source = inspect.getsource(predict_module.predict_video)

for i, line in enumerate(source.splitlines(), 1):
    if "threshold" in line or "parent" in line or "child" in line or "edge" in line:
        print(f"{i:4}: {line}")

  15:     exactly once.  UNet features from each window are reused for edge
  22:     edges : list of (src_idx, tgt_idx, prob, distance) tuples
  36:     ds_arr_t = torch.from_numpy(ds_arr).to(device)   # for predict_edges (original-space coords)
  49:     all_edges: list[tuple[int, int, float, float]] = []
 101:                     det_logits[f_idx][0], t, cfg.det_threshold, pool_k,
 152:             edge_logits_pair = model.predict_edges(
 159:             raw = edge_logits_pair[0]
 160:             if cfg.edge_activation == "softmax":
 170:                     if probs[i, j] > cfg.threshold
 175:             children_count: dict[int, int] = {}
 176:             parents_count: dict[int, int] = {}
 179:                 n_ch = children_count.get(i, 0)
 180:                 n_pa = parents_count.get(j, 0)
 181:                 if cfg.max_children_per_node is not None and n_ch >= cfg.max_children_per_node:
 183:                 if cfg.max_parents_per_node is not None and n_pa >= cfg.max_p

In [57]:

import json
from pathlib import Path

config_path = Path(
    "/kaggle/input/notebooks/thibautgoldsborough/"
    "unet-baseline-inference-submission/"
    "repo/weights/unet_transformer/split_0/config.json"
)

with open(config_path) as f:
    config = json.load(f)

print(json.dumps(config, indent=2))


{
  "unet_out_channels": 32,
  "unet_layers": [
    32,
    64,
    128
  ],
  "downsample": [
    1,
    4,
    4
  ],
  "window_size": 2,
  "pool_kernel_um": 5.0
}


In [ ]:
import torch
import zarr
import scipy
import numpy as np

print("PyTorch :", torch.__version__)
print("Zarr    :", zarr.__version__)
print("SciPy   :", scipy.__version__)
print("NumPy   :", np.__version__)

try:
    import tracksdata
    print("tracksdata: OK")
except Exception as e:
    print("tracksdata: ERROR")
    print(e)

In [ ]:
from scipy.spatial import cKDTree

def inspect_cell_sizes(geff_path):
    graph, _ = geff.read(str(geff_path), backend="networkx")
    by_t = {}
    for n, attrs in graph.nodes(data=True):
        by_t.setdefault(attrs["t"], []).append((attrs["z"], attrs["y"], attrs["x"]))

    dists = []
    for t, pts in by_t.items():
        if len(pts) < 2:
            continue
        tree = cKDTree(pts)
        d, _ = tree.query(pts, k=2)  # nearest OTHER point
        dists.extend(d[:, 1])

    dists = np.array(dists)
    if len(dists) == 0:
        print("Not enough co-occurring points per frame to estimate spacing.")
        return dists

    print(f"Nearest-neighbor cell spacing (voxels): "
          f"min={dists.min():.1f} p25={np.percentile(dists,25):.1f} "
          f"median={np.median(dists):.1f} p75={np.percentile(dists,75):.1f}")
    return dists


# Run on the first training sample that has a paired .geff
_sample_zarr = sorted(train_dir.glob("*.zarr"))[0]
_sample_geff = _sample_zarr.with_suffix(".geff")
if _sample_geff.exists():
    _ = inspect_cell_sizes(_sample_geff)
else:
    print(f"No .geff found next to {_sample_zarr}, skipping size inspection.")


In [ ]:
def diagnose_geff(geff_path):
    graph, _ = geff.read(str(geff_path), backend="networkx")
    by_t = {}
    for n, attrs in graph.nodes(data=True):
        by_t.setdefault(attrs["t"], []).append(n)

    counts = {t: len(nodes) for t, nodes in by_t.items()}
    print(f"{geff_path.name}: {graph.number_of_nodes()} total nodes, "
          f"{len(counts)} timepoints with >=1 node")
    print(f"  nodes/frame: min={min(counts.values())} "
          f"max={max(counts.values())} mean={np.mean(list(counts.values())):.1f}")
    return counts


candidates = sorted(train_dir.glob("*.zarr"))[:10]  # check first 10 samples
best_sample, best_max_count = None, 0

for zp in candidates:
    gp = zp.with_suffix(".geff")
    if not gp.exists():
        continue
    counts = diagnose_geff(gp)
    max_count = max(counts.values())
    if max_count > best_max_count:
        best_max_count = max_count
        best_sample = gp

print(f"\nBest sample for spacing stats: {best_sample} (max {best_max_count} cells/frame)")
if best_sample:
    _ = inspect_cell_sizes(best_sample)

## Measure actual cell size from pixel data

Spacing between cells isn't cell size. Crop a small window around each known cell
center, threshold locally, and measure the connected-component size touching the
center — this gives a real, image-derived voxel count for `min_area`/`max_area`.

In [ ]:
from scipy.ndimage import label as cc_label

def measure_cell_footprints(zarr_path, geff_path, window=8, max_points=30):
    """Crop a small window around each labeled GT centroid, threshold locally,
    and measure the connected-component size touching the center voxel."""
    z = zarr.open(str(zarr_path), mode="r")
    vol = np.asarray(z["0"])  # (T, Z, Y, X)

    graph, _ = geff.read(str(geff_path), backend="networkx")

    areas = []
    points = list(graph.nodes(data=True))[:max_points]

    for n, attrs in points:
        t, z_, y, x = attrs["t"], attrs["z"], attrs["y"], attrs["x"]
        frame = vol[t].astype(np.float32)

        z0, z1 = max(0, z_ - window), min(frame.shape[0], z_ + window)
        y0, y1 = max(0, y - window), min(frame.shape[1], y + window)
        x0, x1 = max(0, x - window), min(frame.shape[2], x + window)
        crop = frame[z0:z1, y0:y1, x0:x1]
        if crop.size == 0:
            continue

        smoothed = gaussian_filter(crop, sigma=1.0)
        try:
            thresh = threshold_otsu(smoothed)
        except ValueError:
            continue
        mask = smoothed > thresh

        labels, _ = cc_label(mask)
        center = (z_ - z0, y - y0, x - x0)
        center = tuple(int(np.clip(center[i], 0, mask.shape[i] - 1)) for i in range(3))
        center_label = labels[center]
        if center_label == 0:
            continue

        area = (labels == center_label).sum()
        areas.append(area)

    areas = np.array(areas)
    if len(areas) == 0:
        print("No valid footprints measured — try a different window size or sample.")
        return areas

    print(f"Measured {len(areas)} cell footprints (voxels): "
          f"min={areas.min()} p25={np.percentile(areas,25):.0f} "
          f"median={np.median(areas):.0f} p75={np.percentile(areas,75):.0f} "
          f"max={areas.max()}")
    return areas


areas = measure_cell_footprints(best_sample.with_suffix(".zarr"), best_sample)

## Measure real frame-to-frame movement

`max_distance` bounds how far ultrack will link a cell between consecutive frames.
Measure this directly from ground-truth tracks: for every real edge, how far did the
cell actually move?

In [ ]:
def measure_frame_to_frame_distance(geff_path, voxel_scale=VOXEL_SCALE):
    graph, _ = geff.read(str(geff_path), backend="networkx")
    coords = {n: np.array([attrs["z"], attrs["y"], attrs["x"]]) * np.array(voxel_scale)
              for n, attrs in graph.nodes(data=True)}

    dists = []
    for u, v in graph.edges():
        d = np.linalg.norm(coords[u] - coords[v])
        dists.append(d)

    dists = np.array(dists)
    if len(dists) == 0:
        print("No edges found in this sample.")
        return dists

    print(f"Frame-to-frame movement (micrometers): "
          f"min={dists.min():.2f} p25={np.percentile(dists,25):.2f} "
          f"median={np.median(dists):.2f} p75={np.percentile(dists,75):.2f} "
          f"max={dists.max():.2f}")
    return dists


move_dists = measure_frame_to_frame_distance(best_sample)

In [ ]:
def compute_foreground_contours(vol, smooth_sigma=1.0):
    """vol: (T, Z, Y, X) array. Returns (foreground, contours), both (T,Z,Y,X)."""
    T = vol.shape[0]
    foreground = np.zeros(vol.shape, dtype=bool)
    contours = np.zeros(vol.shape, dtype=np.float32)

    for t in range(T):
        frame = vol[t].astype(np.float32)
        smoothed = gaussian_filter(frame, sigma=smooth_sigma)

        try:
            thresh = threshold_otsu(smoothed)
        except ValueError:
            thresh = smoothed.max() * 0.5
        foreground[t] = smoothed > thresh

        edge = np.zeros_like(smoothed)
        for zi in range(smoothed.shape[0]):
            edge[zi] = sobel(smoothed[zi])
        e_min, e_max = edge.min(), edge.max()
        contours[t] = (edge - e_min) / (e_max - e_min + 1e-8)

    return foreground, contours
def run_ultrack(foreground, contours, voxel_scale=VOXEL_SCALE,
                 min_area=10, max_area=5000, max_distance=15.0):
    config = MainConfig()
    config.segmentation_config.min_area = min_area
    config.segmentation_config.max_area = max_area
    config.linking_config.max_distance = max_distance

    tracker = Tracker(config)
    tracker.track(foreground=foreground, edges=contours, scale=voxel_scale,
                   overwrite=True)

    tracks_df, graph = tracker.to_tracks_layer()
    return tracks_df, graph, tracker
def tracks_to_submission_rows(tracks_df, graph, dataset_name, row_id_start=0):
    rows = []
    row_id = row_id_start

    tracks_df = tracks_df.sort_values(["track_id", "t"]).reset_index(drop=True)
    node_id_map = {}
    next_node_id = 1

    for _, r in tracks_df.iterrows():
        key = (int(r["track_id"]), int(r["t"]))
        node_id_map[key] = next_node_id
        rows.append(dict(
            id=row_id, dataset=dataset_name, row_type="node",
            node_id=next_node_id, t=int(r["t"]),
            z=int(round(r["z"])), y=int(round(r["y"])), x=int(round(r["x"])),
            source_id=-1, target_id=-1,
        ))
        row_id += 1
        next_node_id += 1

    for track_id, grp in tracks_df.groupby("track_id"):
        grp = grp.sort_values("t")
        ts = grp["t"].tolist()
        for a, b in zip(ts[:-1], ts[1:]):
            src = node_id_map[(int(track_id), int(a))]
            tgt = node_id_map[(int(track_id), int(b))]
            rows.append(dict(
                id=row_id, dataset=dataset_name, row_type="edge",
                node_id=-1, t=-1, z=-1, y=-1, x=-1,
                source_id=src, target_id=tgt,
            ))
            row_id += 1

    tmin = tracks_df.groupby("track_id")["t"].min().to_dict()
    tmax = tracks_df.groupby("track_id")["t"].max().to_dict()
    for child_id, parent_id in graph.items():
        if parent_id is None or parent_id < 0:
            continue
        if parent_id not in tmax or child_id not in tmin:
            continue
        src = node_id_map.get((int(parent_id), int(tmax[parent_id])))
        tgt = node_id_map.get((int(child_id), int(tmin[child_id])))
        if src is None or tgt is None:
            continue
        rows.append(dict(
            id=row_id, dataset=dataset_name, row_type="edge",
            node_id=-1, t=-1, z=-1, y=-1, x=-1,
            source_id=src, target_id=tgt,
        ))
        row_id += 1

    return rows, row_id


def load_sample_volume(zarr_path):
    z = zarr.open(str(zarr_path), mode="r")
    return np.asarray(z["0"])  # shape (T, Z, Y, X)

In [ ]:
def evaluate_one_sample(zarr_path, geff_gt_path, pred_geff_out,
                         min_area=10, max_area=5000, max_distance=15.0,
                         match_threshold_um=3.0):
    vol = load_sample_volume(zarr_path)
    foreground, contours = compute_foreground_contours(vol)
    tracks_df, graph, tracker = run_ultrack(
        foreground, contours, min_area=min_area, max_area=max_area,
        max_distance=max_distance,
    )

    shutil.rmtree(pred_geff_out, ignore_errors=True)
    tracker.to_geff(pred_geff_out)

    gt = load_geff_data(str(geff_gt_path), name="GT")
    pred = load_geff_data(str(pred_geff_out), name="pred")

    results, matched = run_metrics(
        gt_data=gt, pred_data=pred,
        matcher=PointMatcher(threshold=match_threshold_um),
        metrics=[BasicMetrics(), DivisionMetrics()],
    )
    return results


def evaluate_train_samples(train_root, n_samples=3, **kwargs):
    train_root = Path(train_root)
    zarr_paths = sorted(train_root.glob("*.zarr"))[:n_samples]

    all_results = []
    for zp in zarr_paths:
        sample_id = zp.stem
        geff_path = zp.with_suffix(".geff")
        if not geff_path.exists():
            print(f"skip {sample_id}: no .geff ground truth found")
            continue

        print(f"\n=== {sample_id} ===")
        pred_out = f"/kaggle/working/pred_{sample_id}.geff"
        results = evaluate_one_sample(zp, geff_path, pred_out, **kwargs)
        for r in results:
            print(f"  {r['metric']['name']}: {r['results']}")
        all_results.append((sample_id, results))

    return all_results